### ISSUE TITLE
mtime is set as mtime instead of specified <key> when specifying when argument

### ISSUE THREAD

**Issue by vodkapmp** [bradenhilton/yt-dlp-FixupMtime#6] opened 2024-04-19 17:28 UTC
When specifying the `when` argument for running the plugin it defaults to mtime and wont use the specified `<key>` value (upload_date, release_date, etc)
I need to use after_move and not post_process as using post_process seems to happen before yt-dlp sets metadata, which then changes the mtime to current time.

An example is this video: https://www.youtube.com/watch?v=FDqUDoOhKoA
It gets tagged with this mtime: `2024-01-19T10:48:31+00:00`
These are the dates in the info.json:
```
"upload_date": "20230520"
"release_date": "20230520"
```
The metadata is parsed correctly by yt-dlp:
`[MetadataParser] Parsed meta_date from '%(upload_date>%Y-%m-%d)s': '2023-05-20'`

I'm using this command:
`yt-dlp https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:when=after_move;mtime_key=upload_date;mtime_format=%Y-%m-%d`

---

Failing to mtime when using `when=after_move`
```
yt-dlp https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:when=after_move;mtime_key=upload_date;mtime_format=%Y-%m-%d
[youtube] Extracting URL: https://youtu.be/FDqUDoOhKoA
[youtube] FDqUDoOhKoA: Downloading webpage
[youtube] FDqUDoOhKoA: Downloading ios player API JSON
[youtube] FDqUDoOhKoA: Downloading android player API JSON
[youtube] FDqUDoOhKoA: Downloading m3u8 information
[info] FDqUDoOhKoA: Downloading 1 format(s): 616+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 32
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4
[download] 100% of   33.66MiB in 00:00:01 at 18.72MiB/s
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm
[download] 100% of    2.43MiB in 00:00:00 at 24.77MiB/s
[Merger] Merging formats into "絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].webm"
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4 (pass -k to keep)
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm (pass -k to keep)
[FixupMtime] Setting mtime of files to `mtime` (2024-01-19T10:48:31+00:00)
```
Failing to mtime when using `when=post_process`
```
yt-dlp https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:when=post_process;mtime_key=upload_date;mtime_format=%Y-%m-%d
[youtube] Extracting URL: https://youtu.be/FDqUDoOhKoA
[youtube] FDqUDoOhKoA: Downloading webpage
[youtube] FDqUDoOhKoA: Downloading ios player API JSON
[youtube] FDqUDoOhKoA: Downloading android player API JSON
[youtube] FDqUDoOhKoA: Downloading m3u8 information
[info] FDqUDoOhKoA: Downloading 1 format(s): 616+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 32
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4
[download] 100% of   33.66MiB in 00:00:01 at 20.37MiB/s
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm
[download] 100% of    2.43MiB in 00:00:00 at 60.27MiB/s
[Merger] Merging formats into "絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].webm"
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4 (pass -k to keep)
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm (pass -k to keep)
[FixupMtime] Setting mtime of files to `mtime` (2024-01-19T10:48:31+00:00)
```
Working fine when no `when` specified:
```
yt-dlp https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:mtime_key=upload_date;mtime_format=%Y-%m-%d
[youtube] Extracting URL: https://youtu.be/FDqUDoOhKoA
[youtube] FDqUDoOhKoA: Downloading webpage
[youtube] FDqUDoOhKoA: Downloading ios player API JSON
[youtube] FDqUDoOhKoA: Downloading android player API JSON
[youtube] FDqUDoOhKoA: Downloading m3u8 information
[info] FDqUDoOhKoA: Downloading 1 format(s): 616+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 32
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4
[download] 100% of   33.66MiB in 00:00:01 at 29.13MiB/s
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm
[download] 100% of    2.43MiB in 00:00:00 at 58.99MiB/s
[Merger] Merging formats into "絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].webm"
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4 (pass -k to keep)
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm (pass -k to keep)
[FixupMtime] Setting mtime of files to `upload_date` (2023-05-20T00:00:00)
```

**Comment by bradenhilton** [comment] 2024-04-19 18:43
I tried to debug this but I can't reproduce it in either my local repo or the current released version:

```console
❯  c:; cd 'c:\Users\User\yt-dlp-FixupMtime'; & 'c:\Users\User\yt-dlp-FixupMtime\.venv\Scripts\python.exe' 'c:\Users\User\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '57445' '--' '-m' 'yt_dlp' '--ignore-config' '--use-postprocessor' 'FixupMtime:when=after_move;mtime_key=upload_date;mtime_format=%Y-%m-%d' '--' 'https://www.youtube.com/watch?v=FDqUDoOhKoA'
[youtube] Extracting URL: https://www.youtube.com/watch?v=FDqUDoOhKoA
[youtube] FDqUDoOhKoA: Downloading webpage
[youtube] FDqUDoOhKoA: Downloading ios player API JSON
[youtube] FDqUDoOhKoA: Downloading android player API JSON
[youtube] FDqUDoOhKoA: Downloading m3u8 information
[info] FDqUDoOhKoA: Downloading 1 format(s): 616+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 32
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4
[download] 100% of   33.66MiB in 00:00:05 at 5.97MiB/s
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm
[download] 100% of    2.43MiB in 00:00:00 at 16.16MiB/s
[Merger] Merging formats into "絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].webm"
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm (pass -k to keep)
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4 (pass -k to keep)
[FixupMtime] Setting mtime of files to `upload_date` (2023-05-20T00:00:00)

❯ yt-dlp --ignore-config --use-postprocessor 'FixupMtime:when=post_process;mtime_key=upload_date;mtime_format=%Y-%m-%d' -- https://www.youtube.com/watch?v=FDqUDoOhKoA
[youtube] Extracting URL: https://www.youtube.com/watch?v=FDqUDoOhKoA
[youtube] FDqUDoOhKoA: Downloading webpage
[youtube] FDqUDoOhKoA: Downloading ios player API JSON
[youtube] FDqUDoOhKoA: Downloading android player API JSON
[youtube] FDqUDoOhKoA: Downloading m3u8 information
[info] FDqUDoOhKoA: Downloading 1 format(s): 616+251
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 32
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4
[download] 100% of   33.66MiB in 00:00:02 at 11.41MiB/s
[download] Destination: 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm
[download] 100% of    2.43MiB in 00:00:00 at 20.99MiB/s
[Merger] Merging formats into "絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].webm"
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f251.webm (pass -k to keep)
Deleting original file 絶対敵対メチャキライヤー ⧸ 大空スバル × 猫又おかゆ(cover) [FDqUDoOhKoA].f616.mp4 (pass -k to keep)
[FixupMtime] Setting mtime of files to `upload_date` (2023-05-20T00:00:00)
```

**Comment by vodkapmp** [comment] 2024-04-19 19:28
Your reply made me realize that it was actually a very simple solution!
A simple ' before and after the arguments was all that was needed..

This: `yt-dlp --ignore-config https://youtu.be/FDqUDoOhKoA --use-postprocessor 'FixupMtime:when=after_move;mtime_key=upload_date;mtime_format=%Y-%m-%d'` works perfectly

This: `yt-dlp --ignore-config https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:when=after_move;mtime_key=upload_date;mtime_format=%Y-%m-%d` does not

**Comment by bradenhilton** [comment] 2024-04-19 20:24
Your shell likely interprets semicolons as command terminations, which would mean

```console
❯ yt-dlp --ignore-config https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:when=after_move;mtime_key=upload_date;mtime_format=%Y-%m-%d
```

would result in something like

```console
❯ yt-dlp --ignore-config https://youtu.be/FDqUDoOhKoA --use-postprocessor FixupMtime:when=after_move

❯ mtime_key=upload_date

❯ mtime_format=%Y-%m-%d
```

Given that there does not seem to be an issue any more, I will close this.

**Closed by bradenhilton** 2024-04-19 20:24 UTC
